### ISSUE TITLE
The links listed under Developers section in README.md are not found.

### ISSUE THREAD

**Issue by WardJanssen** [trendystore/store#11]
![image](https://cloud.githubusercontent.com/assets/8686354/13016039/af1b211c-d1bc-11e5-98b7-74255f9e5c7c.png)

**Comment by VandeurenGlenn** [comment]
Thanks for tracking down!

**Comment by VandeurenGlenn** [comment]
Hi @WardJanssen, any progress made ?

**Comment by WardJanssen** [comment]
ok lets do it! :-)

**Comment by VandeurenGlenn** [comment]
:+1:

**Comment by VandeurenGlenn** [comment]
@WardJanssen Should I make/send a guide for creating a PR ?

**Comment by VandeurenGlenn** [comment]
@WardJanssen Bes careful when editing comments, as a trendystore member you can edit mine also apparently ... :D

**Comment by VandeurenGlenn** [comment]
closing this since 7d25cdaa749b900ceb4dcf973cca2d766f7a25f3
